- hosts: webserver
  tasks:
    - name: Coleta o hostname
      command: hostname

    - name: Instalar Apache 2
      become: yes
      apt: 
        name: ['apache2', 'php']
        state: present
        update_cache: yes
        
    - name: Iniciar o Servico apache2 no momento do boot
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes 
        
    - name: Iniciar o Servico apache2 no momento do boot
      become: yes
      systemd:
        name: apache2
        masked: no
        state: started
        enabled: yes

 
    - name: Iniciar o Servico apache2 no momento do boot
      become: yes
      systemd:
        name: apache2
        masked: no
        state: started
        enabled: yes
        
    - name: Copiar o website para pasta do apache
      become: yes
      copy:
       src: /home/ubuntu/modulo-ansible/Website_Copy
       dest: /var/www/html/
       owner: root
       group: root
       mode: '0644'

