- hosts: webserver
  tasks:
    - name: Coleta o hostname
      command: hostname

    - name: Instalar Apache 2
      become: yes
      apt: 
        name: ['apache2', 'php']
        state: present
        update_cache: yes
        
    - name: Iniciar o Servico apache2 no momento do boot
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes 